# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
