# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-23 20:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20201221_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupplace',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
