# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pickupplace_the_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routechange',
            name='old_city',
            field=models.CharField(max_length=64, null=True, verbose_name='Old city'),
        ),
    ]
