# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20210309_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='old_pk',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
