# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20210311_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='print_labels',
            field=models.BooleanField(default=True, verbose_name='Print labels from this route'),
        ),
    ]
