# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210315_1337'),
        ('logistics', '0007_auto_20210311_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='routechange',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='state',
            field=models.CharField(max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='routechange',
            name='old_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Old address'),
        ),
        migrations.AlterField(
            model_name='routechange',
            name='old_city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Old city'),
        ),
    ]
