# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_edition_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='copies',
            field=models.IntegerField(blank=True, null=True, verbose_name='Copies'),
        ),
    ]
