# Generated by Django 4.1.4 on 2024-10-04 02:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0013_delete_georefaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="phone_extension",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="Phone extension"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Phone",
            ),
        ),
    ]
