# Generated by Django 4.2 on 2026-05-14 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_distributor_strings(apps, schema_editor):
    Route = apps.get_model("logistics", "Route")
    Distributor = apps.get_model("logistics", "Distributor")
    for route in Route.objects.exclude(distributor_old=""):
        distributor, _ = Distributor.objects.get_or_create(name=route.distributor_old)
        route.distributor = distributor
        route.save(update_fields=["distributor"])


def reverse_migrate_distributor_strings(apps, schema_editor):
    Route = apps.get_model("logistics", "Route")
    for route in Route.objects.filter(distributor__isnull=False):
        route.distributor_old = route.distributor.name
        route.save(update_fields=["distributor_old"])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logistics", "0014_route_phone_extension_alter_route_mobile_and_more"),
    ]

    operations = [
        # 1. Create Distributor model
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "distributor",
                "verbose_name_plural": "distributors",
                "ordering": ("name",),
            },
        ),
        # 2. Rename old CharField to distributor_old (preserves data)
        migrations.RenameField(
            model_name="route",
            old_name="distributor",
            new_name="distributor_old",
        ),
        # 3. Add new FK field (nullable)
        migrations.AddField(
            model_name="route",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logistics.distributor",
                verbose_name="Distributor",
            ),
        ),
        # 4. Data migration: create Distributor objects from old string values
        migrations.RunPython(migrate_distributor_strings, reverse_migrate_distributor_strings),
        # 5. Remove the old string field
        migrations.RemoveField(
            model_name="route",
            name="distributor_old",
        ),
    ]
