# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201214_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccontactfilter',
            name='last_time_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamiccontactfilter',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'At least one of the products'), (2, 'All products'), (3, b'Newsletters')]),
        ),
    ]
