# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201228_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcampaignstatus',
            old_name='seller_resolution',
            new_name='seller',
        ),
    ]
