# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='label_message',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
