# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='old_pk',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[(b'State 1', b'State 1'), (b'State 2', b'State 2')], default='Montevideo', max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='old_pk',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(b'O', b'Other'), (b'D', b'Debit card'), (b'S', b'Cash payment')], max_length=1, null=True, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscription_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Economical reasons'), (2, b'Did not like the product'), (3, b'Problem with payment type'), (4, b'Did not receive the product')], null=True, verbose_name='Unsubscription reason'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='old_pk',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
