# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210311_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(b'S', 'Subscription'), (b'N', 'Newsletter'), (b'D', 'Discount'), (b'O', 'Other')], db_index=True, default='O', max_length=1),
        ),
    ]
