# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210311_1417'),
        ('core', '0006_auto_20210311_1844'),
    ]

    operations = [
    ]
