# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20210311_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='Montevideo', max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscription_reason',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Unsubscription reason'),
        ),
    ]
