# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210315_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[(b'S', 'Campaign start'), (b'C', 'Call'), (b'M', 'E-mail'), (b'L', 'Link hit'), (b'E', 'Event participation'), (b'I', 'In-place visit')], max_length=1, null=True),
        ),
    ]
