# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20210329_1350'),
        ('core', '0010_auto_20210319_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactproducthistory',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.Seller'),
        ),
    ]
