# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactproducthistory_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundle_product',
        ),
        migrations.AddField(
            model_name='product',
            name='offerable',
            field=models.BooleanField(default=False, verbose_name='Allow offer'),
        ),
    ]
