# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210401_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='label_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contact'),
        ),
    ]
