# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-22 15:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_issuestatus_category'),
        ('core', '0014_auto_20210408_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Seller'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9\xf1\xfc\xe1\xe9\xed\xf3\xfa\xd1\xdc\xc1\xc9\xcd\xd3\xda _'.\\-]*$", 'This name only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Name'),
        ),
    ]
