# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210422_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ocupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Ocupation', verbose_name='Ocupation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Seller'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Subtype', verbose_name='Subtype'),
        ),
        migrations.AlterField(
            model_name='contactproducthistory',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Campaign'),
        ),
        migrations.AlterField(
            model_name='contactproducthistory',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Seller'),
        ),
        migrations.AlterField(
            model_name='contactproducthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Seller', verbose_name='Seller'),
        ),
    ]
