# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210423_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='envelope',
            field=models.NullBooleanField(default=False, verbose_name='Envelope'),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='free_envelope',
            field=models.NullBooleanField(default=False, verbose_name='Free envelope'),
        ),
    ]
