# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210423_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='has_envelope',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Paid envelope'), (2, 'Free envelope')], null=True, verbose_name='Envelope'),
        ),
    ]
