# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210616_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactcampaignstatus',
            unique_together=set([('contact', 'campaign')]),
        ),
    ]
