# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210624_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[(b'P', 'Promotion'), (b'N', 'Normal'), (b'F', 'Gift'), (b'S', 'Staff')], default='N', max_length=1),
        ),
    ]
