# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210629_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcampaignstatus',
            name='resolution_reason',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Acepta llamada / va a pensarlo'), (2, 'Motivos econ\xf3micos'), (3, 'Fuera de zona'), (4, 'Le interesa para m\xe1s adelante'), (5, 'Mala experiencia'), (6, 'No aplica a la campa\xf1a'), (7, 'No da motivos'), (8, 'No lee / No tiene tiempo'), (9, 'No lleg\xf3 promoci\xf3n'), (10, 'No responde'), (11, 'No sab\xeda que se hab\xeda registrado'), (12, 'N\xfamero y email incorrectos'), (13, 'Ya es suscriptor')], null=True),
        ),
        migrations.AlterField(
            model_name='contactcampaignstatus',
            name='campaign_resolution',
            field=models.CharField(blank=True, choices=[(b'SP', 'Started promotion'), (b'AS', 'Already a subscriber'), (b'DN', 'Do not call anymore'), (b'EP', 'Error in promotion'), (b'LO', 'Logistics'), (b'NI', 'Not interested'), (b'S1', 'Success with promotion'), (b'S2', 'Success with direct sale')], max_length=2, null=True),
        ),
    ]
