# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-01 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210730_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='seller',
        ),
    ]
