# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210801_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='send_bill_copy_by_email',
            field=models.BooleanField(default=True, verbose_name='Send bill copy by email'),
        ),
    ]
