# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210910_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unsubscription_products',
            field=models.ManyToManyField(related_name='unsubscriptions', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscription_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Complete unsubscription'), (2, 'Partial unsubscription'), (3, 'Product change'), (4, 'Upgrade')], null=True, verbose_name='Unsubscription type'),
        ),
    ]
