# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210913_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcampaignstatus',
            name='campaign_reject_reason',
        ),
        migrations.AddField(
            model_name='contactcampaignstatus',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactcampaignstatus',
            name='campaign_resolution',
            field=models.CharField(blank=True, choices=[(b'SP', 'Started promotion'), (b'AS', 'Already a subscriber'), (b'DN', 'Do not call anymore'), (b'EP', 'Error in promotion'), (b'LO', 'Logistics'), (b'NI', 'Not interested'), (b'S1', 'Success with promotion'), (b'S2', 'Success with direct sale'), (b'SC', 'Scheduled'), (b'CL', 'Call later'), (b'UN', 'Cannot find contact')], max_length=2, null=True),
        ),
    ]
