# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211013_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='card_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
