# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20211021_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccontactfilter',
            name='debtor_contacts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Exclude debtors'), (2, 'Only debtors')], null=True),
        ),
    ]
