# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_dynamiccontactfilter_debtor_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='label_message',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='re_routed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='resubscription_date',
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
