# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211124_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'One-shot'), (5, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[(b'S', 'Campaign start'), (b'C', 'Call'), (b'M', 'E-mail'), (b'L', 'Link hit'), (b'W', 'WhatsApp message or other apps'), (b'E', 'Event participation'), (b'I', 'In-place visit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Positive for discount, negative for surcharge', max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, choices=[(b'AP', 'Awaiting payment'), (b'NC', 'Not consolidated'), (b'OK', 'Normal'), (b'PA', 'Paused'), (b'DE', 'End because of debt'), (b'NE', 'Normal end'), (b'ER', 'Error')], max_length=2, null=True),
        ),
    ]
