# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220120_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edition_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'One-shot'), (5, 'Others')], default=None, null=True),
        ),
    ]
