# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220304_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-type', 'id'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='contactcampaignstatus',
            name='resolution_reason',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
