# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220607_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cms_date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CMS join date'),
        ),
    ]
