# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_contact_cms_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('S', 'Campaign start'), ('C', 'Call'), ('M', 'E-mail'), ('L', 'Link hit'), ('W', 'WhatsApp message or other apps'), ('E', 'Event participation'), ('I', 'In-place visit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='direction',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('D', 'Delayed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], max_length=50, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='contactcampaignstatus',
            name='campaign_resolution',
            field=models.CharField(blank=True, choices=[('SP', 'Started promotion'), ('AS', 'Already a subscriber'), ('DN', 'Do not call anymore'), ('EP', 'Error in promotion'), ('LO', 'Logistics'), ('NI', 'Not interested'), ('S1', 'Success with promotion'), ('S2', 'Success with direct sale'), ('SC', 'Scheduled'), ('CL', 'Call later'), ('UN', 'Cannot find contact')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contactproducthistory',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Paused'), ('R', 'Resumed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dynamiccontactfilter',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'At least one of the products'), (2, 'All products'), (3, 'Newsletters')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('S', 'Subscription'), ('N', 'Newsletter'), ('D', 'Discount'), ('P', 'Percentage discount'), ('A', 'Advanced discount'), ('O', 'Other')], db_index=True, default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('AP', 'Awaiting payment'), ('NC', 'Not consolidated'), ('OK', 'Normal'), ('PA', 'Paused'), ('DE', 'End because of debt'), ('NE', 'Normal end'), ('ER', 'Error')], default='OK', max_length=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('P', 'Promotion'), ('N', 'Normal'), ('F', 'Gift'), ('S', 'Staff')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscription_channel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'E-Mail'), (2, 'Phone')], null=True, verbose_name='Unsubscription channel'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(blank=True, choices=[('impresion', 'Impression'), ('impresion_fs', 'Imperssion Weekend')], max_length=255, verbose_name='type'),
        ),
    ]
