# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-31 14:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_auto_20220819_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9ñüáéíóúÑÜÁÉÍÓÚ _'.\\-]*$", 'This name only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Name')),
                ('id_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identifcation Document')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Work phone')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email')),
                ('no_email', models.BooleanField(default=False, verbose_name='No email')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Primary'), (2, 'Incomplete secondary'), (3, 'Complete secondary'), (4, 'Incomplete university'), (5, 'Complete university'), (6, 'Postgraduate'), (100, "Doesn't want to inform")], null=True, verbose_name='Education')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('private_birthdate', models.BooleanField(default=False, verbose_name='Private birthdate')),
                ('protected', models.BooleanField(default=False, verbose_name='Protected')),
                ('protection_reason', models.TextField(blank=True, null=True, verbose_name='Protection reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('allow_polls', models.BooleanField(default=True, verbose_name='Allows polls')),
                ('allow_promotions', models.BooleanField(default=True, verbose_name='Allows promotions')),
                ('cms_date_joined', models.DateTimeField(blank=True, null=True, verbose_name='CMS join date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Institution', verbose_name='Institution')),
                ('ocupation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Ocupation', verbose_name='Ocupation')),
                ('referrer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Contact', verbose_name='Referrer')),
                ('subtype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Subtype', verbose_name='Subtype')),
            ],
            options={
                'verbose_name': 'historical contact',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
