# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20221017_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(max_length=500, verbose_name='value'),
        ),
    ]
