# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20221025_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='do_not_show',
            field=models.BooleanField(default=False, help_text='Do not show in picture/google maps list'),
        ),
        migrations.AddField(
            model_name='address',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='address_pictures/'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='do_not_show',
            field=models.BooleanField(default=False, help_text='Do not show in picture/google maps list'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
