# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20221028_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temporary_discount_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
