# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_product_temporary_discount_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoNotCallNumber',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
