# Generated by Django 4.1.4 on 2023-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_donotcallnumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_implicit_discount',
            field=models.BooleanField(default=False, verbose_name='Has implicit discount'),
        ),
    ]
