# Generated by Django 4.1.4 on 2023-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_donotcallnumber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
