# Generated by Django 4.1.4 on 2023-07-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'offerable': True, 'type': 'S'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
