# Generated by Django 4.1.4 on 2023-05-12 17:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_product_target_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_georef_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="city_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="georef_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="state_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="address_georef_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="city_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="georef_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="state_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[],
                default="Montevideo",
                max_length=50,
                null=True,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[],
                default="Montevideo",
                max_length=50,
                null=True,
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
