# Generated by Django 4.1.4 on 2023-09-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_emailbounceactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailbounceactionlog',
            options={'ordering': ('-created', 'email')},
        ),
    ]
