# Generated by Django 4.1.4 on 2023-09-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_emailbounceactionlog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo_ref_address',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='geo_ref_address',
        ),
    ]
