# Generated by Django 4.1.4 on 2023-10-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_emailbounceactionlog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreplacement',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='suggested', max_length=15),
        ),
    ]
