# Generated by Django 4.1.4 on 2023-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_emailreplacement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='unsubscription_requested',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='unsubscription_requested',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='Montevideo', max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[], default='Montevideo', max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(blank=True, default='Montevideo', max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='state',
            field=models.CharField(blank=True, choices=[], default='Montevideo', max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='Payment type'),
        ),
    ]
