# Generated by Django 4.1.4 on 2024-01-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_historicalsubscription_unsubscription_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer_id',
        ),
    ]
