# Generated by Django 4.1.4 on 2024-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_remove_historicalsubscription_card_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ("-active", "priority", "name"),
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("can_add_free_subscription", "Can add free subscription")
                ],
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="free_subscription_requested_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human resources"),
                    ("AD", "Advertisement"),
                    ("MA", "Management"),
                    ("JD", "Journalism direction"),
                    ("PR", "Promotion"),
                ],
                max_length=2,
                null=True,
                verbose_name="Free subscription requested by",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="free_subscription_requested_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human resources"),
                    ("AD", "Advertisement"),
                    ("MA", "Management"),
                    ("JD", "Journalism direction"),
                    ("PR", "Promotion"),
                ],
                max_length=2,
                null=True,
                verbose_name="Free subscription requested by",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 - Highest"),
                    (2, "2 - High"),
                    (3, "3 - Mid"),
                    (4, "4 - Low"),
                    (5, "5 - Lowest"),
                ],
                default=3,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
