# Generated by Django 4.1.4 on 2024-03-04 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0060_alter_campaign_options_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubscription",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Validated"),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="validated_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validated date"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Validated"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="validated_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validated date"
            ),
        ),
    ]
