# Generated by Django 4.1.4 on 2024-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_historicalsubscription_validated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
    ]
