# Generated by Django 4.1.4 on 2024-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_alter_contact_phone_alter_historicalcontact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailtrainList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mailtrain List",
                "verbose_name_plural": "Mailtrain Lists",
            },
        ),
    ]
