# Generated by Django 4.1.4 on 2024-07-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_mailtrainlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='renewal_type',
            field=models.CharField(choices=[('A', 'Auto-renewal'), ('M', 'One-time')], default='A', max_length=2, verbose_name='Renewal type'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_type',
            field=models.CharField(choices=[('A', 'Auto-renewal'), ('M', 'One-time')], default='A', max_length=2, verbose_name='Renewal type'),
        ),
    ]
