# Generated by Django 4.1.4 on 2024-08-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_address_country_contact_id_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdDocumentType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='contact',
        #     name='id_document_type',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalcontact',
        #     name='id_document_type',
        # ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('P', 'Person'), ('C', 'Company')], default='P', max_length=1, null=True, verbose_name='Contact type'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('P', 'Person'), ('C', 'Company')], default='P', max_length=1, null=True, verbose_name='Contact type'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal code'),
        ),
        migrations.AddField(
            model_name='contact',
            name='id_document_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.iddocumenttype', verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='id_document_cat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.iddocumenttype', verbose_name='Document type'),
        ),
    ]
