# Generated by Django 4.1.4 on 2024-08-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_iddocumenttype_remove_contact_id_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id_document_cat',
            new_name='id_document_type',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='id_document_cat',
            new_name='id_document_type',
        ),
    ]
