# Generated by Django 4.1.4 on 2024-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_rename_id_document_cat_contact_id_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billing_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Monthly'), (90, 'Quarterly'), (365, 'Annual'), (720, 'Biannual'), (0, 'One-shot')], default=30, null=True, verbose_name='Billing frequency'),
        ),
        migrations.AddField(
            model_name='product',
            name='renewal_type',
            field=models.CharField(blank=True, choices=[('A', 'Automatic'), ('M', 'Manual'), ('R', 'Renewal')], default='A', max_length=1, null=True, verbose_name='Renewal type'),
        ),
    ]
