# Generated by Django 4.1.4 on 2024-09-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='billing_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Monthly'), (90, 'Quarterly'), (365, 'Annual'), (730, 'Biannual'), (0, 'One-shot')], default=30, null=True, verbose_name='Billing frequency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='renewal_type',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('A', 'Automatic'), ('R', 'Renewal')], default='A', max_length=1, null=True, verbose_name='Renewal type'),
        ),
    ]
