# Generated by Django 4.1.4 on 2024-09-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_product_billing_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='billing_contact',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contact', verbose_name='Billing Contact'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_subscriptions', to='core.contact', verbose_name='Billing Contact'),
        ),
    ]
