# Generated by Django 4.1.4 on 2024-10-30 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_contact_phone_extension_contact_work_phone_extension_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_id',
            new_name='city_georef_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state_id',
            new_name='state_georef_id',
        ),
        migrations.RenameField(
            model_name='historicaladdress',
            old_name='city_id',
            new_name='city_georef_id',
        ),
        migrations.RenameField(
            model_name='historicaladdress',
            old_name='state_id',
            new_name='state_georef_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9ñüáéíóúÑÜÁÉÍÓÚ _'.\\-]*$", 'This field only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9ñüáéíóúÑÜÁÉÍÓÚ _'.\\-]*$", 'This field only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9ñüáéíóúÑÜÁÉÍÓÚ _'.\\-]*$", 'This field only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[@A-Za-z0-9ñüáéíóúÑÜÁÉÍÓÚ _'.\\-]*$", 'This field only supports alphanumeric characters, at, apostrophes, spaces, hyphens, underscores, and periods.')], verbose_name='Name'),
        ),
    ]
