# Generated by Django 4.1.4 on 2024-10-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country_new',
            field=models.ForeignKey(blank=True, db_column='country_fk', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_new',
            field=models.ForeignKey(blank=True, db_column='state_fk', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='country_new',
            field=models.ForeignKey(blank=True, db_column='country_fk', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='state_new',
            field=models.ForeignKey(blank=True, db_column='state_fk', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.state', verbose_name='State'),
        ),
    ]
