# Generated by Django 4.1.4 on 2024-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_remove_old_country_state_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country_old",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Country (old)"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_old",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="State (old)",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalAddress",
        ),
    ]
