# Generated by Django 4.1.4 on 2024-11-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_activity_created_by_historicalactivity_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubscriptionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('months_duration', models.PositiveIntegerField(help_text='Number of months this period represents.')),
                ('description', models.TextField(blank=True, help_text='Optional description for this period, if needed.')),
            ],
            options={
                'verbose_name': 'Product Subscription Period',
                'verbose_name_plural': 'Product Subscription Periods',
                'ordering': ['months_duration'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'id', 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='product',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Duration in months'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='direction',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out'), ('N', 'Internal'), ('R', 'Renewal')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='direction',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Out'), ('N', 'Internal'), ('R', 'Renewal')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='type',
            field=models.CharField(choices=[('P', 'Promotion'), ('N', 'Normal'), ('F', 'Gift'), ('S', 'Staff'), ('C', 'Complementary')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('P', 'Promotion'), ('N', 'Normal'), ('F', 'Gift'), ('S', 'Staff'), ('C', 'Complementary')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activityresponse'),
        ),
        migrations.AddField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activitytopic'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='response',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.activityresponse'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='topic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.activitytopic'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubscriptionperiod'),
        ),
    ]
