# Generated by Django 4.1.4 on 2024-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_activityresponse_activitytopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offerable',
            field=models.BooleanField(default=False, help_text='Allow product to be shown in the new subscription forms', verbose_name='Allow offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='renewal_type',
            field=models.CharField(blank=True, choices=[('A', 'Automatic'), ('M', 'Manual')], default='A', max_length=1, null=True, verbose_name='Renewal type'),
        ),
    ]
