# Generated by Django 4.1.4 on 2024-11-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_product_offerable_alter_product_renewal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='terms_and_conditions')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('terms_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.termsandconditions')),
            ],
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.termsandconditions', verbose_name='Terms and conditions'),
        ),
        migrations.AddField(
            model_name='product',
            name='terms_and_conditions',
            field=models.ManyToManyField(through='core.TermsAndConditionsProduct', to='core.termsandconditions'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.termsandconditions', verbose_name='Terms and conditions'),
        ),
    ]
