# Generated by Django 4.1.4 on 2024-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_termsandconditions_termsandconditionsproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('can_add_free_subscription', 'Can add free subscription'), ('can_add_corporate_subscription', 'Can add corporate subscription')], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='number_of_subscriptions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='override_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='number_of_subscriptions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='override_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='type',
            field=models.CharField(choices=[('P', 'Promotion'), ('N', 'Normal'), ('F', 'Gift'), ('S', 'Staff'), ('C', 'Corporate'), ('A', 'Affiliate')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('P', 'Promotion'), ('N', 'Normal'), ('F', 'Gift'), ('S', 'Staff'), ('C', 'Corporate'), ('A', 'Affiliate')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='terms_and_conditions'),
        ),
    ]
