# Generated by Django 4.1.4 on 2024-11-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='parent_subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.subscription', verbose_name='Parent subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_subscriptions', to='core.subscription', verbose_name='Parent subscription'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='number_of_subscriptions',
            field=models.IntegerField(default=1, help_text='Number of subscriptions to create, more than 1 for corporate subscriptions', verbose_name='Number of subscriptions'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='override_price',
            field=models.IntegerField(blank=True, help_text='Override the price of the subscription, useful for corporate subscriptions', null=True, verbose_name='Override price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_subscriptions',
            field=models.IntegerField(default=1, help_text='Number of subscriptions to create, more than 1 for corporate subscriptions', verbose_name='Number of subscriptions'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_price',
            field=models.IntegerField(blank=True, help_text='Override the price of the subscription, useful for corporate subscriptions', null=True, verbose_name='Override price'),
        ),
    ]
