# Generated by Django 4.1.4 on 2024-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_historicalsubscription_parent_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MercadoPago ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='renewal_type',
            field=models.CharField(blank=True, choices=[('A', 'Automatic'), ('M', 'Manual'), ('X', 'Both')], default='A', max_length=1, null=True, verbose_name='Renewal type'),
        ),
    ]
