# Generated by Django 4.1.13 on 2024-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_product_mercadopago_id_alter_product_renewal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='billing_mode',
            field=models.CharField(choices=[('F', 'Per Frequency'), ('X', 'Fixed Price'), ('C', 'Custom')], default='F', help_text='How the product is billed. Fixed uses the price set in the product, per frequency uses the price calculated from the products in the subscription with the frequency set in the product.', max_length=1, verbose_name='Billing mode'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='Frequency of billing in months'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, help_text='Frequency of billing in months'),
        ),
    ]
