# Generated by Django 4.2.11 on 2024-12-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_product_options_product_billing_mode_and_more'),
        ('core', '0086_businessentitytype_persontype_alter_product_options_and_more'),
    ]

    operations = [
    ]
