# Generated by Django 4.2.11 on 2024-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_paymentmethod_paymenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='creation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
