# Generated by Django 4.1.13 on 2025-01-31 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_historicalsubscription_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Purchase date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Purchase date'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='renewal_type',
            field=models.CharField(choices=[('A', 'Auto-renewal subscription'), ('M', 'One-time subscription')], default='A', max_length=2, verbose_name='Renewal type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_type',
            field=models.CharField(choices=[('A', 'Auto-renewal subscription'), ('M', 'One-time subscription')], default='A', max_length=2, verbose_name='Renewal type'),
        ),
    ]
