# Generated by Django 4.1.13 on 2025-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_historicalsubscription_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='zoho_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zoho Sync Date'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='zoho_synced',
            field=models.BooleanField(default=False, verbose_name='Zoho Synced'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='zoho_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zoho Sync Date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='zoho_synced',
            field=models.BooleanField(default=False, verbose_name='Zoho Synced'),
        ),
    ]
