# Generated by Django 4.1.13 on 2025-04-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_historicalsubscription_zoho_sync_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city_fk',
            field=models.ForeignKey(blank=True, db_column='city_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='City'),
        ),
    ]
