# Generated by Django 4.2.19 on 2025-04-19 00:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_historicalsubscription_zoho_sync_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=100,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
