# Generated by Django 4.1.13 on 2025-04-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_city_address_city_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
    ]
