# Generated by Django 4.1.13 on 2025-04-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_product_name_alter_product_slug'),
        ('core', '0096_alter_state_code'),
    ]

    operations = [
    ]
