# Generated by Django 4.1.13 on 2025-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityresponse',
            options={'ordering': ['name'], 'verbose_name': 'activity response', 'verbose_name_plural': 'activity responses'},
        ),
        migrations.AlterModelOptions(
            name='activitytopic',
            options={'ordering': ['name'], 'verbose_name': 'activity topic', 'verbose_name_plural': 'activity topics'},
        ),
        migrations.AlterModelOptions(
            name='contactcampaignstatus',
            options={'ordering': ['id'], 'verbose_name': 'Contact Campaign Status', 'verbose_name_plural': 'Contact Campaign Statuses'},
        ),
        migrations.AlterModelOptions(
            name='contactproducthistory',
            options={'ordering': ['id'], 'verbose_name': 'Contact Product History', 'verbose_name_plural': 'Contact Product Histories'},
        ),
        migrations.AlterModelOptions(
            name='donotcallnumber',
            options={'ordering': ['number'], 'verbose_name': 'Do Not Call Number', 'verbose_name_plural': 'Do Not Call Numbers'},
        ),
        migrations.AlterModelOptions(
            name='dynamiccontactfilter',
            options={'ordering': ['id'], 'verbose_name': 'Dynamic Contact Filter', 'verbose_name_plural': 'Dynamic Contact Filters'},
        ),
        migrations.AlterModelOptions(
            name='historicalpricerule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Price Rule', 'verbose_name_plural': 'historical Price Rules'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['name'], 'verbose_name': 'Payment Type', 'verbose_name_plural': 'Payment Types'},
        ),
        migrations.AlterModelOptions(
            name='pricerule',
            options={'ordering': ['id'], 'verbose_name': 'Price Rule', 'verbose_name_plural': 'Price Rules'},
        ),
        migrations.AlterModelOptions(
            name='productbundle',
            options={'ordering': ['id'], 'verbose_name': 'Product Bundle', 'verbose_name_plural': 'Product Bundles'},
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the address. It can be a reference to the address or the name of the person', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
