# Generated by Django 4.1.13 on 2025-05-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0027_sellerconsoleaction"),
        ("core", "0098_alter_activityresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="seller_console_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.sellerconsoleaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalactivity",
            name="seller_console_action",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="support.sellerconsoleaction",
            ),
        ),
    ]
