# Generated by Django 4.2 on 2025-06-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0027_sellerconsoleaction"),
        ("core", "0099_activity_seller_console_action_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionproduct",
            options={
                "verbose_name": "Subscription Product",
                "verbose_name_plural": "Subscription Products",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Campaign start"),
                    ("C", "Call"),
                    ("M", "E-mail"),
                    ("L", "Link hit"),
                    ("W", "WhatsApp message or other apps"),
                    ("E", "Event participation"),
                    ("I", "In-place visit"),
                    ("N", "Internal"),
                ],
                max_length=1,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="asap",
            field=models.BooleanField(default=False, verbose_name="ASAP"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="direction",
            field=models.CharField(
                choices=[
                    ("I", "In"),
                    ("O", "Out"),
                    ("N", "Internal"),
                    ("R", "Renewal"),
                ],
                default="O",
                max_length=1,
                verbose_name="Direction",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="priority",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Highest"),
                    (2, "High"),
                    (3, "Normal"),
                    (4, "Low"),
                    (5, "Lowest"),
                ],
                default=3,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.activityresponse",
                verbose_name="Response",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="seller_console_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.sellerconsoleaction",
                verbose_name="Seller console action",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Completed"), ("D", "Delayed")],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.activitytopic",
                verbose_name="Topic",
            ),
        ),
        migrations.AlterField(
            model_name="activityresponse",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="activityresponse",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="activitytopic",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="activitytopic",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Campaign start"),
                    ("C", "Call"),
                    ("M", "E-mail"),
                    ("L", "Link hit"),
                    ("W", "WhatsApp message or other apps"),
                    ("E", "Event participation"),
                    ("I", "In-place visit"),
                    ("N", "Internal"),
                ],
                max_length=1,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="asap",
            field=models.BooleanField(default=False, verbose_name="ASAP"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="direction",
            field=models.CharField(
                choices=[
                    ("I", "In"),
                    ("O", "Out"),
                    ("N", "Internal"),
                    ("R", "Renewal"),
                ],
                default="O",
                max_length=1,
                verbose_name="Direction",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="priority",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Highest"),
                    (2, "High"),
                    (3, "Normal"),
                    (4, "Low"),
                    (5, "Lowest"),
                ],
                default=3,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.activityresponse",
                verbose_name="Response",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="seller_console_action",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="support.sellerconsoleaction",
                verbose_name="Seller console action",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Completed"), ("D", "Delayed")],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.activitytopic",
                verbose_name="Topic",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Frequency of billing in months",
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="payment_certificate",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Payment certificate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="rut",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="UTR"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Awaiting payment"),
                    ("NC", "Not consolidated"),
                    ("OK", "Normal"),
                    ("PA", "Paused"),
                    ("DE", "End because of debt"),
                    ("NE", "Normal end"),
                    ("ER", "Error"),
                ],
                default="OK",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="type",
            field=models.CharField(
                choices=[
                    ("P", "Promotion"),
                    ("N", "Normal"),
                    ("F", "Gift"),
                    ("S", "Staff"),
                    ("C", "Corporate"),
                    ("A", "Affiliate"),
                ],
                default="N",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="updated_from",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.subscription",
                verbose_name="Updated from",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Frequency of billing in months",
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificates/",
                verbose_name="Payment certificate",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="products",
            field=models.ManyToManyField(
                through="core.SubscriptionProduct",
                to="core.product",
                verbose_name="Products",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="rut",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="UTR"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("AP", "Awaiting payment"),
                    ("NC", "Not consolidated"),
                    ("OK", "Normal"),
                    ("PA", "Paused"),
                    ("DE", "End because of debt"),
                    ("NE", "Normal end"),
                    ("ER", "Error"),
                ],
                default="OK",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="type",
            field=models.CharField(
                choices=[
                    ("P", "Promotion"),
                    ("N", "Normal"),
                    ("F", "Gift"),
                    ("S", "Staff"),
                    ("C", "Corporate"),
                    ("A", "Affiliate"),
                ],
                default="N",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscription",
                verbose_name="Updated from",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="copies",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Copies"),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="label_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.contact",
                verbose_name="Label contact",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="label_message",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Label message"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.seller",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="special_instructions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Special instructions"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionproduct",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
