# Generated by Django 4.2 on 2025-07-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_alter_subscriptionproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="work_phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50, verbose_name="Work phone"
            ),
        ),
        migrations.AlterField(
            model_name="contactcampaignstatus",
            name="campaign_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SP", "Started promotion"),
                    ("AS", "Already a subscriber"),
                    ("DN", "Do not call anymore"),
                    ("EP", "Error in promotion"),
                    ("LO", "Logistics"),
                    ("NI", "Not interested"),
                    ("S1", "Success with promotion"),
                    ("S2", "Success with direct sale"),
                    ("SC", "Scheduled"),
                    ("CL", "Call later"),
                    ("UN", "Cannot find contact"),
                    ("CW", "Close without contact"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="work_phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50, verbose_name="Work phone"
            ),
        ),
    ]
