# Generated by Django 4.2 on 2025-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_alter_contact_work_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="work_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="Work phone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="work_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="Work phone",
            ),
        ),
    ]
