# Generated by Django 4.2.19 on 2025-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_alter_contact_work_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="old_pk",
        ),
        migrations.AddField(
            model_name="product",
            name="cms_subscription_type",
            field=models.SlugField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="CMS subscription type",
            ),
        ),
    ]
