# Generated by Django 4.1.13 on 2025-08-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0029_sellerconsoleaction_campaign_status"),
        ("core", "0103_remove_product_old_pk_product_cms_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactcampaignstatus",
            name="last_console_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.sellerconsoleaction",
            ),
        ),
    ]
