# Generated by Django 4.2.19 on 2025-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_remove_product_old_pk_product_cms_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mercadopago_id",
            field=models.CharField(
                blank=True,
                help_text="If MercadoPago product sync is enabled, this field is auto-filled when this product is created.",
                max_length=255,
                null=True,
                verbose_name="MercadoPago ID",
            ),
        ),
    ]
