# Generated by Django 4.1.13 on 2025-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_alter_product_mercadopago_id"),
        ("core", "0104_contactcampaignstatus_last_console_action"),
    ]

    operations = []
