# Generated by Django 4.2.19 on 2025-08-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_merge_20250808_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Completed"),
                    ("D", "Delayed"),
                    ("E", "Expired"),
                ],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("C", "Completed"),
                    ("D", "Delayed"),
                    ("E", "Expired"),
                ],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
