# Generated by Django 4.1.13 on 2025-08-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_alter_activity_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advanceddiscount",
            options={
                "verbose_name": "Advanced Discount",
                "verbose_name_plural": "Advanced Discounts",
            },
        ),
        migrations.AlterModelOptions(
            name="businessentitytype",
            options={
                "verbose_name": "Business Entity Type",
                "verbose_name_plural": "Business Entity Types",
            },
        ),
        migrations.AlterModelOptions(
            name="emailbounceactionlog",
            options={
                "ordering": ("-created", "email"),
                "verbose_name": "Email Bounce Action Log",
                "verbose_name_plural": "Email Bounce Action Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="emailreplacement",
            options={
                "ordering": ("status", "domain"),
                "verbose_name": "Email Replacement",
                "verbose_name_plural": "Email Replacements",
            },
        ),
        migrations.AlterModelOptions(
            name="iddocumenttype",
            options={
                "verbose_name": "ID Document Type",
                "verbose_name_plural": "ID Document Types",
            },
        ),
        migrations.AlterModelOptions(
            name="persontype",
            options={
                "verbose_name": "Person Type",
                "verbose_name_plural": "Person Types",
            },
        ),
        migrations.AlterModelOptions(
            name="termsandconditions",
            options={
                "verbose_name": "Terms and Conditions",
                "verbose_name_plural": "Terms and Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="termsandconditionsproduct",
            options={
                "verbose_name": "Terms and Conditions Product",
                "verbose_name_plural": "Terms and Conditions Products",
            },
        ),
        migrations.AddField(
            model_name="activityresponse",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.activitytopic",
                verbose_name="Topic",
            ),
        ),
        migrations.AlterField(
            model_name="businessentitytype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="businessentitytype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="iddocumenttype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="persontype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="persontype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="billing_priority",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Billing priority"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="edition_frequency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Daily"),
                    (2, "Weekly"),
                    (3, "Monthly"),
                    (4, "One-shot"),
                    (5, "Others"),
                ],
                default=None,
                null=True,
                verbose_name="Edition frequency",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="target_product",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"offerable": True, "type": "S"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Target product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="temporary_discount_months",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Temporary discount months"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "Subscription"),
                    ("N", "Newsletter"),
                    ("D", "Discount"),
                    ("P", "Percentage discount"),
                    ("A", "Advanced discount"),
                    ("O", "Other"),
                ],
                db_index=True,
                default="O",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weekday",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                    (8, "All week"),
                    (9, "Weekdays"),
                    (10, "Weekends"),
                ],
                default=None,
                null=True,
                verbose_name="Weekday",
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Description for internal use",
                max_length=255,
                null=True,
                verbose_name="Description code",
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="terms_and_conditions",
                verbose_name="PDF File",
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="version",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditionsproduct",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="termsandconditionsproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="termsandconditionsproduct",
            name="terms_and_conditions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.termsandconditions",
                verbose_name="Terms and Conditions",
            ),
        ),
    ]
