# Generated by Django 4.1.13 on 2025-09-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_alter_advanceddiscount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cms_subscription_type",
            field=models.SlugField(
                blank=True,
                help_text="The subscription type of the SubscriptionPrice object in utopia-cms, used for synchronization with this Product. Also used by the CMS front-end to build the related subscription form page URL and for traffic tracking tools.",  # noqa
                max_length=64,
                null=True,
                unique=True,
                verbose_name="CMS subscription type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subscription_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.productsubscriptionperiod",
                verbose_name="Subscription Period",
            ),
        ),
    ]
