# Generated by Django 4.1.13 on 2025-09-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_alter_advanceddiscount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cms_subscription_type",
            field=models.SlugField(
                blank=True,
                help_text="Enter the product name. Unsupported spaces or other characters will be replaced with hyphens when saving. Used for the URL slug of the product form in the web subscription and for traffic tracking tools.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="CMS subscription type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subscription_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.productsubscriptionperiod",
                verbose_name="Subscription Period",
            ),
        ),
    ]
