# Generated by Django 4.2.19 on 2025-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_alter_product_cms_subscription_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cms_subscription_type",
            field=models.SlugField(
                blank=True,
                help_text="The subscription type of the SubscriptionPrice object in utopia-cms, used for synchronization with this Product. Also used by the CMS front-end to build the related subscription form page URL and for traffic tracking tools.",  # noqa
                max_length=100,
                null=True,
                unique=True,
                verbose_name="CMS subscription type",
            ),
        ),
    ]
