# Generated by Django 4.2 on 2025-11-04 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_alter_product_cms_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionproduct",
            name="original_datetime",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Date and time when the subscription product was originally created, regardless of the subscription. This product might have been inherited from another subscription.",
                null=True,
                verbose_name="Original date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="unsubscription_reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Does not like content"),
                    (2, "Economical reasons"),
                    (3, "Other"),
                ],
                help_text="Reason why the user finished definitively the subscription",
                null=True,
                verbose_name="Unsubscription reason",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="target_product",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription product this discount applies to. Only active subscription products are shown.",
                limit_choices_to={"active": True, "type": "S"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Target product",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="unsubscription_reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Does not like content"),
                    (2, "Economical reasons"),
                    (3, "Other"),
                ],
                help_text="Reason why the user finished definitively the subscription",
                null=True,
                verbose_name="Unsubscription reason",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
    ]
