# Generated by Django 4.2.19 on 2025-10-23 23:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_alter_product_cms_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="emailbounceactionlog",
            name="email",
            field=core.fields.LowercaseEmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Billing email"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Billing email"
            ),
        ),
    ]
