# Generated by Django 4.2.19 on 2025-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_alter_address_email_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mercadopago_skip_sync",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this product will not be synchronized with a MercadoPago plan until this field is unchecked and the object is saved. This means that the field is disabled if the product has a MercadoPago ID set.",
                verbose_name="Do not sync this product with a MercadoPago plan",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mercadopago_id",
            field=models.CharField(
                blank=True,
                help_text="If MercadoPago product sync is enabled, this field is auto-filled when this product is saved.",
                max_length=255,
                null=True,
                verbose_name="MercadoPago ID",
            ),
        ),
    ]
