# Generated by Django 4.2 on 2025-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_subscriptionproduct_original_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Retention"),
                    ("P", "Promotion"),
                    ("S", "Staff"),
                    ("O", "Other"),
                ],
                help_text="Category of the discount. Mandatory if the product type is discount.",
                max_length=1,
                null=True,
                verbose_name="Discount category",
            ),
        ),
    ]
