# Generated by Django 4.2 on 2025-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0111_product_discount_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("can_add_free_subscription", "Can add free subscription"),
                    (
                        "can_add_corporate_subscription",
                        "Can add corporate subscription",
                    ),
                    ("can_offer_retention", "Can offer retention"),
                ],
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (17, "Retention"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                    (5, "Retention"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (17, "Retention"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                    (5, "Retention"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
    ]
