# Generated by Django 4.2 on 2025-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Structured data for storing additional activity information (e.g., unsubscription data)",
                null=True,
                verbose_name="Metadata",
            ),
        ),
        migrations.AddField(
            model_name="historicalactivity",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Structured data for storing additional activity information (e.g., unsubscription data)",
                null=True,
                verbose_name="Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (17, "Retention"),
                    (18, "All products removed"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                    (5, "Retention"),
                    (6, "All products removed"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="inactivity_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Normal end"),
                    (2, "Paused"),
                    (3, "Added products"),
                    (4, "Changed products"),
                    (13, "Debtor"),
                    (16, "Debtor, automatic unsubscription"),
                    (17, "Retention"),
                    (18, "All products removed"),
                    (99, "N/A"),
                ],
                help_text="Reason for the inactivity of the subscription",
                null=True,
                verbose_name="Inactivity reason",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="unsubscription_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Complete unsubscription"),
                    (2, "Partial unsubscription"),
                    (3, "Changed products"),
                    (4, "Added products"),
                    (5, "Retention"),
                    (6, "All products removed"),
                ],
                null=True,
                verbose_name="Unsubscription type",
            ),
        ),
    ]
