# Generated by Django 4.2 on 2026-01-19 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0113_activity_metadata_historicalactivity_metadata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "permissions": [("can_merge_addresses", "Can merge addresses")],
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
    ]
