# Generated by Django 4.2.19 on 2026-01-14 12:10

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_activity_metadata_historicalactivity_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mercadopago_skip_sync",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this product will not be synchronized with a MercadoPago plan until this field is unchecked and the object is saved. This means that the field is disabled if the product has a MercadoPago ID set.",
                verbose_name="Do not sync this product with a MercadoPago plan",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="emailbounceactionlog",
            name="email",
            field=core.fields.LowercaseEmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Billing email"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mercadopago_id",
            field=models.CharField(
                blank=True,
                help_text="If MercadoPago product sync is enabled, this field is auto-filled when this product is saved.",
                max_length=255,
                null=True,
                verbose_name="MercadoPago ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Billing email"
            ),
        ),
    ]
