# Generated by Django 4.2 on 2026-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_alter_address_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubscription",
            name="free_subscription_requested_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human resources"),
                    ("AD", "Advertisement"),
                    ("MA", "Management"),
                    ("JD", "Newsroom"),
                    ("PR", "Promotion"),
                ],
                max_length=2,
                null=True,
                verbose_name="Free subscription requested by",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="free_subscription_requested_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human resources"),
                    ("AD", "Advertisement"),
                    ("MA", "Management"),
                    ("JD", "Newsroom"),
                    ("PR", "Promotion"),
                ],
                max_length=2,
                null=True,
                verbose_name="Free subscription requested by",
            ),
        ),
    ]
