# Generated by Django 4.2 on 2026-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0116_alter_historicalsubscription_free_subscription_requested_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcampaignstatus",
            name="campaign_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SP", "Started promotion"),
                    ("AS", "Already a subscriber"),
                    ("DN", "Do not call anymore"),
                    ("EP", "Error in promotion"),
                    ("LO", "Logistics"),
                    ("NI", "Not interested"),
                    ("S1", "Success with promotion"),
                    ("S2", "Success with direct sale"),
                    ("SC", "Scheduled"),
                    ("CL", "Call later"),
                    ("NF", "Not found"),
                    ("UN", "Cannot find contact"),
                    ("CW", "Close without contact"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
