# Generated by Django 4.2 on 2026-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0117_add_not_found_campaign_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="added_products",
            field=models.ManyToManyField(
                blank=True, related_name="subscriptions_added", to="core.product"
            ),
        ),
    ]
