# Generated by Django 4.2 on 2026-08-26 17:49

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0120_activity_last_in_campaign_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTakeoverRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_email",
                    core.fields.LowercaseEmailField(
                        max_length=254, verbose_name="Requested email"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("edit_contact", "Contact edit"),
                            ("new_subscription", "New subscription"),
                            ("create_contact", "Contact creation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Origin",
                    ),
                ),
                (
                    "preview_detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Preview detail"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="Resolution note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved at"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takeover_requests",
                        to="core.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved by",
                    ),
                ),
            ],
            options={
                "verbose_name": "email takeover request",
                "verbose_name_plural": "email takeover requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_takeover_email", "Can approve and execute email takeovers")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="emailtakeoverrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("contact", "requested_email"),
                name="unique_pending_email_takeover_request",
            ),
        ),
    ]
