# Generated by Django 4.2 on 2026-10-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_add_lost_schedule_campaign_resolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iddocumenttype",
            options={
                "ordering": ["id"],
                "verbose_name": "ID Document Type",
                "verbose_name_plural": "ID Document Types",
            },
        ),
    ]
