# Generated by Django 4.1.4 on 2024-01-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0003_alter_advertisementactivity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adpurchaseorder",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_order_agency",
                to="advertisement.advertiser",
                verbose_name="Advertiser",
            ),
        ),
        migrations.AddField(
            model_name="adpurchaseorder",
            name="agency_commission",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adpurchaseorder",
            name="seller_commission",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advertisementactivity",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="priority",
            field=models.CharField(
                choices=[("1", "High"), ("2", "Mid"), ("3", "Low")],
                default="2",
                max_length=2,
                verbose_name="Importance",
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="type",
            field=models.CharField(
                choices=[("PU", "Public"), ("PR", "Private")],
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
