# Generated by Django 4.1.4 on 2024-01-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_alter_campaign_options_alter_subscription_options_and_more"),
        ("advertisement", "0004_adpurchaseorder_agency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="main_seller",
        ),
        migrations.AlterField(
            model_name="adpurchaseorder",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.advertisementseller",
                verbose_name="Seller",
            ),
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Billing name",
                    ),
                ),
                (
                    "billing_id_document",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Billing ID document",
                    ),
                ),
                (
                    "utr",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unique taxpayer reference",
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Billing phone",
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Billing email field",
                    ),
                ),
                (
                    "agency_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contact",
                        verbose_name="Main contact",
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.address",
                        verbose_name="Billing address",
                    ),
                ),
                (
                    "main_seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_main_seller",
                        to="advertisement.advertisementseller",
                        verbose_name="Seller",
                    ),
                ),
                (
                    "other_contacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="other_agencies",
                        to="core.contact",
                        verbose_name="Other contacts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.AddField(
            model_name="advertisementactivity",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.agency",
                verbose_name="Agency",
            ),
        ),
        migrations.AlterField(
            model_name="adpurchaseorder",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.agency",
                verbose_name="Agency",
            ),
        ),
    ]
