# Generated by Django 4.1.4 on 2024-01-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0005_remove_adpurchaseorder_main_seller_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="ads",
        ),
        migrations.AddField(
            model_name="ad",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisement.adpurchaseorder",
            ),
        ),
    ]
