# Generated by Django 4.1.4 on 2024-01-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0006_remove_adpurchaseorder_ads_ad_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="billing_email",
        ),
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="billing_id_document",
        ),
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="billing_name",
        ),
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="billing_phone",
        ),
        migrations.RemoveField(
            model_name="adpurchaseorder",
            name="utr",
        ),
        migrations.AddField(
            model_name="agency",
            name="priority",
            field=models.CharField(
                choices=[("1", "High"), ("2", "Mid"), ("3", "Low")],
                default="2",
                max_length=2,
                verbose_name="Importance",
            ),
        ),
        migrations.AlterField(
            model_name="adpurchaseorder",
            name="bill_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_agency",
                to="advertisement.agency",
                verbose_name="Bill to agency",
            ),
        ),
    ]
