# Generated by Django 4.1.4 on 2024-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0007_remove_adpurchaseorder_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertiser",
            name="billing_address",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Billing address"
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="billing_address",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Billing address"
            ),
        ),
    ]
