# Generated by Django 4.1.4 on 2024-02-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_alter_campaign_options_alter_subscription_options_and_more"),
        (
            "advertisement",
            "0009_remove_agency_agency_contact_agency_main_contact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="agent",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contact",
            ),
        ),
    ]
