# Generated by Django 4.1.4 on 2024-02-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0010_agent_notes_alter_agent_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="adpurchaseorder",
            name="date_billed",
            field=models.DateField(blank=True, null=True, verbose_name="Date billed"),
        ),
    ]
