# Generated by Django 4.1.4 on 2024-10-02 18:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0001_squashed_0011_adpurchaseorder_date_billed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adpurchaseorder",
            options={
                "permissions": [
                    ("can_set_billed", "Can set the purchase order as billed")
                ],
                "verbose_name": "Ad purchase order",
                "verbose_name_plural": "Ad purchase orders",
            },
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Billing phone",
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="billing_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Billing phone",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="Phone",
            ),
        ),
    ]
