# Generated by Django 4.2.19 on 2025-10-23 23:50

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0012_alter_adpurchaseorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertiser",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Billing email field",
            ),
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="billing_email",
            field=core.fields.LowercaseEmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Billing email field",
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=core.fields.LowercaseEmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
