# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20210311_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
