# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 13:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20210323_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatus',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
