# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20210329_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='category',
            field=models.CharField(blank=True, choices=[(b'L', 'Logistics'), (b'I', 'Invoicing'), (b'C', 'Contents'), (b'W', 'Web'), (b'S', 'Service'), (b'O', 'Community')], max_length=2, null=True),
        ),
    ]
