# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20210423_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='label_message',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='category',
            field=models.CharField(choices=[(b'AC', 'Address change'), (b'PD', 'Start of pause'), (b'PA', 'End of pause')], max_length=2, verbose_name='Type'),
        ),
    ]
