# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-06 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_auto_20210616_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'ordering': ['name']},
        ),
    ]
