# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-06 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20210729_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='issuesubcategory',
            options={'ordering': ['category', 'name']},
        ),
    ]
