# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220218_1325'),
        ('support', '0013_auto_20210806_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='category',
            field=models.CharField(choices=[(b'AC', 'Address change'), (b'PD', 'Start of pause'), (b'PA', 'End of pause'), (b'PS', 'Start of partial pause'), (b'PE', 'End of partial pause')], max_length=2, verbose_name='Type'),
        ),
    ]
