# Generated by Django 4.1.4 on 2024-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0018_salesrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="sale_type",
            field=models.CharField(
                choices=[("F", "Full"), ("P", "Partial")], default="F", max_length=1
            ),
        ),
    ]
