# Generated by Django 4.1.4 on 2024-03-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_historicalsubscription_validated_and_more"),
        ("support", "0019_salesrecord_sale_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.campaign",
                verbose_name="Campaign",
            ),
        ),
    ]
