# Generated by Django 4.1.4 on 2024-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0020_salesrecord_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="commission_for_payment_type",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Commission for payment type",
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="commission_for_products_sold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Commission for products sold",
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="commission_for_subscription_frequency",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Commission for subscription frequency",
            ),
        ),
    ]
