# Generated by Django 4.1.4 on 2024-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0022_salesrecord_can_be_commissioned"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="total_commission_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total commission value",
            ),
        ),
    ]
