# Generated by Django 4.1.4 on 2024-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0023_salesrecord_total_commission_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
