# Generated by Django 4.1.4 on 2024-04-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0024_alter_salesrecord_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="support.seller",
                verbose_name="Seller",
            ),
        ),
    ]
