# Generated by Django 4.1.4 on 2024-11-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_alter_salesrecord_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalscheduledtask',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Scheduled task', 'verbose_name_plural': 'historical Scheduled tasks'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['execution_date'], 'verbose_name': 'Scheduled task', 'verbose_name_plural': 'Scheduled tasks'},
        ),
    ]
