# Generated by Django 4.1.13 on 2025-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0026_alter_historicalscheduledtask_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerConsoleAction",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Seller Console Action",
                "verbose_name_plural": "Seller Console Actions",
                "ordering": ("name",),
            },
        ),
    ]
