# Generated by Django 4.1.13 on 2025-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0027_sellerconsoleaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerconsoleaction",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Success"),
                    ("D", "Declined"),
                    ("P", "Pending"),
                    ("N", "No contact"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
