# Generated by Django 4.1.13 on 2025-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0028_sellerconsoleaction_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerconsoleaction",
            name="campaign_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Not yet contacted"),
                    (2, "Contacted"),
                    (3, "Called, could not contact"),
                    (4, "Ended with contact"),
                    (5, "Ended without contact"),
                    (6, "Switch to morning"),
                    (7, "Switch to afternoon/evening"),
                ],
                help_text="Campaign status to set when this action is performed",
                null=True,
            ),
        ),
    ]
