# Generated by Django 4.1.13 on 2025-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0029_sellerconsoleaction_campaign_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalissue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Issue",
                "verbose_name_plural": "historical Issues",
            },
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterModelOptions(
            name="issuestatus",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="issuesubcategory",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Issue Subcategory",
                "verbose_name_plural": "Issue Subcategories",
            },
        ),
        migrations.AlterField(
            model_name="sellerconsoleaction",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Success"),
                    ("D", "Declined"),
                    ("P", "Pending"),
                    ("N", "No contact"),
                    ("C", "Scheduled"),
                    ("L", "Call later"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
