# Generated by Django 4.2 on 2026-01-27 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0031_sellerconsoleaction_campaign_resolution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalissue",
            name="date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Date of the issue",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Date of the issue",
                verbose_name="Date",
            ),
        ),
        migrations.CreateModel(
            name="IssueResolution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.issuesubcategory",
                        verbose_name="Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Resolution",
                "verbose_name_plural": "Issue Resolutions",
                "ordering": ["subcategory", "name"],
            },
        ),
        migrations.AddField(
            model_name="historicalissue",
            name="resolution",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="support.issueresolution",
                verbose_name="Resolution",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="resolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.issueresolution",
                verbose_name="Resolution",
            ),
        ),
    ]
