# Generated by Django 4.2 on 2026-02-10 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0032_alter_historicalissue_date_alter_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "permissions": [
                    (
                        "can_access_community_console",
                        "Can access community management console",
                    )
                ],
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
            },
        ),
    ]
