# Generated by Django 4.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0033_add_community_console_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "permissions": [
                    (
                        "can_access_community_console",
                        "Can access community management console",
                    ),
                    (
                        "can_manage_community_console",
                        "Can manage community console (assign issues)",
                    ),
                ],
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
            },
        ),
    ]
