# Generated by Django 4.2 on 2026-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0034_add_community_manager_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerconsoleaction",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Success"),
                    ("D", "Declined"),
                    ("P", "Pending"),
                    ("N", "No contact"),
                    ("C", "Scheduled"),
                    ("L", "Call later"),
                    ("F", "Not found"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sellerconsoleaction",
            name="campaign_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SP", "Started promotion"),
                    ("AS", "Already a subscriber"),
                    ("DN", "Do not call anymore"),
                    ("EP", "Error in promotion"),
                    ("LO", "Logistics"),
                    ("NI", "Not interested"),
                    ("S1", "Success with promotion"),
                    ("S2", "Success with direct sale"),
                    ("SC", "Scheduled"),
                    ("CL", "Call later"),
                    ("NF", "Not found"),
                    ("UN", "Cannot find contact"),
                    ("CW", "Close without contact"),
                ],
                help_text="Campaign resolution to set when this action is performed",
                max_length=2,
                null=True,
            ),
        ),
    ]
