# Generated by Django 4.2 on 2026-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0034_add_community_manager_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="date_modified",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Date modified"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date modified"
            ),
        ),
    ]
