# Generated by Django 4.2 on 2026-03-06 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0035_add_not_found_action_type"),
        ("support", "0036_reset_issue_date_modified_to_null"),
    ]

    operations = []
