# Generated by Django 4.2 on 2026-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0038_alter_seller_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("F", "Full"),
                    ("P", "Partial"),
                    ("C", "Product Change"),
                    ("R", "Retention"),
                ],
                default="F",
                max_length=1,
            ),
        ),
    ]
