# Generated by Django 4.2 on 2026-04-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0039_salesrecord_add_product_change_and_retention_sale_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("justified", models.BooleanField(verbose_name="Justified")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "absence reason",
                "verbose_name_plural": "absence reasons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
            ],
            options={
                "verbose_name": "attendance record",
                "verbose_name_plural": "attendance records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("start_time", models.TimeField(verbose_name="Start time")),
                ("end_time", models.TimeField(verbose_name="End time")),
            ],
            options={
                "verbose_name": "shift",
                "verbose_name_plural": "shifts",
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="seller",
            name="call_center",
            field=models.BooleanField(
                default=False, verbose_name="Works in call center?"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="support.shift",
                verbose_name="Shift",
            ),
        ),
        migrations.CreateModel(
            name="SellerAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent")],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("shift_start", models.TimeField(verbose_name="Shift start")),
                ("shift_end", models.TimeField(verbose_name="Shift end")),
                (
                    "absence_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="support.absencereason",
                        verbose_name="Absence reason",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="support.attendancerecord",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support.seller",
                        verbose_name="Seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "seller attendance",
                "verbose_name_plural": "seller attendances",
                "unique_together": {("record", "seller")},
            },
        ),
    ]
