# Generated by Django 4.2 on 2026-09-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0041_add_lost_schedule_campaign_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="commission_overridden",
            field=models.BooleanField(
                default=False, verbose_name="Commission overridden"
            ),
        ),
    ]
