# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[(b'R', 'RedPagos'), (b'T', 'Tarjeta de cr\xe9dito'), (b'M', 'MercadoPago'), (b'E', 'Efectivo'), (b'B', 'D\xe9bito Brou'), (b'I', 'e-Brou'), (b'P', 'PayPal'), (b'X', 'Error')], max_length=1, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('billing_date', models.DateField()),
                ('dpp', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[(b'P', 'Pending'), (b'R', 'Starting'), (b'S', 'Started'), (b'A', 'Aborted'), (b'C', 'Completed'), (b'E', 'Completed with errors')], default='P', max_length=1)),
                ('processed_contacts', models.IntegerField(default=0)),
                ('subscriber_amount', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('exclude', models.ManyToManyField(to='core.Contact')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'start',
                'verbose_name_plural': 'billings',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('serie', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'credit notes',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('service_from', models.DateField()),
                ('service_to', models.DateField()),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[(b'R', 'RedPagos'), (b'T', 'Tarjeta de cr\xe9dito'), (b'M', 'MercadoPago'), (b'E', 'Efectivo'), (b'B', 'D\xe9bito Brou'), (b'I', 'e-Brou'), (b'P', 'PayPal'), (b'X', 'Error')], max_length=2, verbose_name='Payment type')),
                ('debited', models.BooleanField(default=False, verbose_name='Debited')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('payment_reference', models.CharField(blank=True, max_length=32, null=True, verbose_name='Payment reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Invoice notes')),
                ('canceled', models.BooleanField(default=False, editable=False, verbose_name='Canceled')),
                ('cancelation_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Cancelation date')),
                ('uncollectible', models.BooleanField(default=False, verbose_name='Uncollectible')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=36, null=True)),
                ('serie', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('pdf', models.FileField(blank=True, editable=False, null=True, upload_to=b'facturas/%Y/%m/%d/')),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address')),
                ('billing_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing State')),
                ('billing_city', models.CharField(blank=True, max_length=64, null=True, verbose_name='Billing City')),
                ('billing_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Billing Identifcation Document')),
                ('billing_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Name')),
                ('route', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('old_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Billing')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contact')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subscription')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service_from', models.DateField(blank=True, null=True)),
                ('service_to', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'I', 'Item'), (b'D', 'Discount'), (b'R', 'Surcharge')], default='I', max_length=1)),
                ('type_dr', models.CharField(blank=True, choices=[(b'1', 'Value'), (b'2', 'Percentage')], max_length=1, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subscription')),
            ],
            options={
                'ordering': ['invoice'],
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
        migrations.CreateModel(
            name='CreditNoteCopy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invoicing.creditnote',),
        ),
        migrations.CreateModel(
            name='InvoiceCopy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invoicing.invoice',),
        ),
        migrations.CreateModel(
            name='InvoiceItemCopy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invoicing.invoiceitem',),
        ),
    ]
