# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = []
