# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20210226_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='old_pk',
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_type',
            field=models.CharField(blank=True, choices=[(b'O', b'Other'), (b'D', b'Debit card'), (b'S', b'Cash payment')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[(b'O', b'Other'), (b'D', b'Debit card'), (b'S', b'Cash payment')], max_length=2, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=b'path/to/folder/in/media/'),
        ),
    ]
