# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20210226_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='old_pk',
        ),
    ]
