# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20210311_1419'),
    ]

    operations = []
