# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20210423_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='print_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
