# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-17 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20221017_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0007_auto_20210811_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCreditNote',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('serie', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical credit note',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('service_from', models.DateField()),
                ('service_to', models.DateField()),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('payment_type', models.CharField(max_length=2, verbose_name='Payment type')),
                ('debited', models.BooleanField(default=False, verbose_name='Debited')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('payment_reference', models.CharField(blank=True, max_length=32, null=True, verbose_name='Payment reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Invoice notes')),
                ('canceled', models.BooleanField(default=False, editable=False, verbose_name='Canceled')),
                ('cancelation_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Cancelation date')),
                ('uncollectible', models.BooleanField(default=False, verbose_name='Uncollectible')),
                ('print_date', models.DateField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, editable=False, max_length=36, null=True)),
                ('serie', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('pdf', models.TextField(blank=True, editable=False, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address')),
                ('billing_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing State')),
                ('billing_city', models.CharField(blank=True, max_length=64, null=True, verbose_name='Billing City')),
                ('billing_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Billing Identifcation Document')),
                ('billing_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Name')),
                ('route', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical invoice',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Starting'), ('S', 'Started'), ('A', 'Aborted'), ('C', 'Completed'), ('E', 'Completed with errors')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='facturas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='type',
            field=models.CharField(choices=[('I', 'Item'), ('D', 'Discount'), ('R', 'Surcharge')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='type_dr',
            field=models.CharField(blank=True, choices=[('1', 'Value'), ('2', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='billing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.Billing'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Contact'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Subscription'),
        ),
        migrations.AddField(
            model_name='historicalcreditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoicing.Invoice'),
        ),
    ]
