# Generated by Django 4.1.4 on 2023-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20221017_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcreditnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical credit note', 'verbose_name_plural': 'historical credit notes'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical invoice', 'verbose_name_plural': 'historical invoices'},
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_type',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcreditnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_type',
            field=models.CharField(choices=[('M', 'Mastercard'), ('V', 'Visa'), ('C', 'Cash')], max_length=2, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('M', 'Mastercard'), ('V', 'Visa'), ('C', 'Cash')], max_length=2, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='path/to/folder/in/media/'),
        ),
    ]
