# Generated by Django 4.1.4 on 2023-09-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_alter_historicalcreditnote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='type_dr',
            field=models.CharField(blank=True, choices=[('1', 'Value'), ('2', 'Percentage')], default='1', max_length=1, null=True),
        ),
    ]
