# Generated by Django 4.1.4 on 2024-09-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_product_billing_days_and_more'),
        ('invoicing', '0011_historicalinvoice_fiscal_invoice_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago_data', to='core.contact')),
            ],
            options={
                'verbose_name': 'Mercado Pago Data',
                'verbose_name_plural': 'Mercado Pago Data',
            },
        ),
    ]
