# Generated by Django 4.1.4 on 2024-11-10 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0012_mercadopagodata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["creation_date"],
                "permissions": [
                    ("can_download_pdf", "Can download PDF"),
                    ("can_cancel_invoice", "Can cancel invoice"),
                    ("can_generate_invoices", "Can generate invoices"),
                    ("can_send_duplicate_via_email", "Can send duplicate via email"),
                    ("can_send_to_mercadopago", "Can send to MercadoPago"),
                ],
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
    ]
