# Generated by Django 4.2.11 on 2024-12-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_paymentmethod_paymenttype_and_more'),
        ('invoicing', '0014_alter_invoiceitem_amount_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_method_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Payment method used to pay for the subscription, for example: 'Cash', 'Credit Card', 'Debit Card', 'Bank Transfer', etc.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_type_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Payment type used to pay for the subscription, for example: 'American Express', 'Visa', 'Mastercard', etc.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymenttype', verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='payment_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method_fk',
            field=models.ForeignKey(blank=True, help_text="Payment method used to pay for the subscription, for example: 'Cash', 'Credit Card', 'Debit Card', 'Bank Transfer', etc.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentmethod', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type_fk',
            field=models.ForeignKey(blank=True, help_text="Payment type used to pay for the subscription, for example: 'American Express', 'Visa', 'Mastercard', etc.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymenttype', verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
