# Generated by Django 4.1.13 on 2024-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_historicalinvoice_payment_method_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing City'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Name'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='billing_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing State'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing City'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing State'),
        ),
    ]
