# Generated by Django 4.2.11 on 2024-12-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_historicalinvoice_payment_method_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='old_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='old_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
