# Generated by Django 4.2.11 on 2024-12-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_alter_historicalinvoice_billing_city_and_more'),
        ('invoicing', '0016_historicalinvoice_old_pk_invoice_old_pk'),
    ]

    operations = [
    ]
