# Generated by Django 4.1.13 on 2024-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_merge_20241218_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcreditnote',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
