# Generated by Django 4.1.4 on 2025-01-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0018_creditnote_amount_historicalcreditnote_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["creation_date"],
                "permissions": [
                    ("can_download_pdf", "Can download PDF"),
                    ("can_cancel_invoice", "Can cancel invoice"),
                    ("can_generate_invoices", "Can generate invoices"),
                    ("can_send_duplicate_via_email", "Can send duplicate via email"),
                    ("can_send_to_mercadopago", "Can send to MercadoPago"),
                    ("can_send_to_provider", "Can send to provider"),
                ],
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Payment reference",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Payment reference",
            ),
        ),
    ]
