# Generated by Django 4.1.13 on 2025-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('M', 'Mastercard'), ('V', 'Visa'), ('C', 'Cash')], max_length=2, null=True, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('M', 'Mastercard'), ('V', 'Visa'), ('C', 'Cash')], max_length=2, null=True, verbose_name='Payment type'),
        ),
    ]
