# Generated by Django 4.1.13 on 2025-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_historicalinvoice_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='billing_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Country'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Country'),
        ),
    ]
