# Generated by Django 4.1.13 on 2025-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_historicalinvoice_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='consecutive_payment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consecutive_payment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
