# Generated by Django 4.1.13 on 2025-09-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_alter_product_cms_subscription_type_and_more"),
        ("invoicing", "0025_historicalinvoice_consecutive_payment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditnote",
            options={
                "verbose_name": "credit note",
                "verbose_name_plural": "credit notes",
            },
        ),
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "ordering": ["invoice"],
                "verbose_name": "Invoice item",
                "verbose_name_plural": "Invoice items",
            },
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="invoicing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="serie",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1,
                null=True,
                verbose_name="Serie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="invoicing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="serie",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1,
                null=True,
                verbose_name="Serie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="creation_date",
            field=models.DateField(verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="expiration_date",
            field=models.DateField(verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="pdf",
            field=models.TextField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="print_date",
            field=models.DateField(blank=True, null=True, verbose_name="Print date"),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="serie",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1,
                null=True,
                verbose_name="Serie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="service_from",
            field=models.DateField(verbose_name="Service From"),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="service_to",
            field=models.DateField(verbose_name="Service To"),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="creation_date",
            field=models.DateField(verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="expiration_date",
            field=models.DateField(verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pdf",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to="invoices",
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="print_date",
            field=models.DateField(blank=True, null=True, verbose_name="Print date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="serie",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=1,
                null=True,
                verbose_name="Serie",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="service_from",
            field=models.DateField(verbose_name="Service From"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="service_to",
            field=models.DateField(verbose_name="Service To"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount",
                max_digits=10,
                verbose_name="Total amount",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="copies",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Copies"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Discount",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoicing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per copy",
                max_digits=10,
                null=True,
                verbose_name="Price per copy",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="service_from",
            field=models.DateField(blank=True, null=True, verbose_name="Service from"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="service_to",
            field=models.DateField(blank=True, null=True, verbose_name="Service to"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="type",
            field=models.CharField(
                choices=[("I", "Item"), ("D", "Discount"), ("R", "Surcharge")],
                default="I",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="type_dr",
            field=models.CharField(
                blank=True,
                choices=[("1", "Value"), ("2", "Percentage")],
                default="1",
                max_length=1,
                null=True,
                verbose_name="Type Discount/Surcharge",
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
