# Generated by Django 4.1.13 on 2025-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoicing",
            "0026_alter_creditnote_options_alter_invoiceitem_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Payment reference",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Payment reference",
            ),
        ),
    ]
