# Generated by Django 4.1.13 on 2025-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0027_alter_historicalinvoice_payment_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreditnote",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalcreditnote",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
