# Generated by Django 4.1.13 on 2025-09-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0028_creditnote_created_at_creditnote_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="transaction_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Transaction Number"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transaction_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Transaction Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="consecutive_payment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Consecutive Payment"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="fiscal_invoice_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Fiscal Invoice Code"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="internal_provider_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Internal Provider Text"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="route",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Route"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="invoicing.transactiontype",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="consecutive_payment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Consecutive Payment"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fiscal_invoice_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Fiscal Invoice Code"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="internal_provider_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Internal Provider Text"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="route",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Route"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicing.transactiontype",
                verbose_name="Transaction Type",
            ),
        ),
    ]
