# Generated by Django 4.1.13 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0029_historicalinvoice_transaction_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditnote",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Updated at"
            ),
        ),
    ]
