# Generated by Django 4.2.19 on 2025-12-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0031_mercadopagodata_contact_to_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercadopagodata",
            name="preapproval_id",
            field=models.CharField(
                blank=True,
                help_text="This field is intended to be populated automatically when the subscription is created in MercadoPago and will never change. In order to keep data consistency, when the field is set, critical operations over this CRM related Subscription will be restricted, otherwise, recurring payments coming from MercadoPago can fail to be processed.",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="MercadoPago preapproval (aka subscription) id",
            ),
        ),
    ]
